server:
  port: 31200
spring:
  application:
    name: xc_service_manage_course
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/xc_course?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: 1234
      driverClassName: com.mysql.jdbc.Driver
      initialSize: 5  #初始建立连接数量
      minIdle: 5  #最小连接数量
      maxActive: 20 #最大连接数量
      maxWait: 10000  #获取连接最大等待时间，毫秒
      testOnBorrow: true #申请连接时检测连接是否有效
      testOnReturn: false #归还连接时检测连接是否有效
      timeBetweenEvictionRunsMillis: 60000 #配置间隔检测连接是否有效的时间（单位是毫秒）
      minEvictableIdleTimeMillis: 300000  #连接在连接池的最小生存时间（毫秒）
pagehelper:
  helper-dialect: mysql
mybatis:
  type-aliases-package: com.czxy.xuecheng.domain.course  #给JavaBean起别名
  mapper-locations: classpath:mybatis/mappers/*.xml #加载所有的xml
  configuration:
    map-underscore-to-camel-case: true  #支持驼峰命名  user_name --> userName
eureka:
  client:
    registerWithEureka: true #服务注册开关
    fetchRegistry: true #服务发现开关
    serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址，多个中间用逗号分隔
      defaultZone: http://localhost:50101/eureka/
  instance:
    prefer-ip-address:  true  #将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port} #指定实例id
course-publish:
  siteId: 5b30cba5f58b4411fc6cb1e5
  templateId: 5f216dc17119ae67a88b0f19
  dataUrlPre: http://localhost:31200/course/courseview/
  pagePhysicalPath: /course/detail/
  pageWebPath: /course/detail/
  previewUrl: http://www.xuecheng.com/cms/preview/